### ISSUE TITLE
.profile does not include old PATH definitions correctly

### ISSUE THREAD

**Issue by Piiit** [linuxmint/mintupgrade-legacy#1]
After upgrade from 17.3 Cinnamon to 18, my .profile file contains the correct PATH declaration.  However,
it gets included within an IF statement... see $HOME/mypath that gets not loaded when there is no $HOME/bin folder...

```
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$HOME/mypath:$PATH"
fi
```

**Comment by clefebvre** [comment]
I've got this:

# set PATH so it includes user's private bin if it exists

if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

bash is the package providing /etc/skel/.profile.

**Comment by Piiit** [comment]
Hi,
maybe I haven't explained things accurate.

I've added a new path to the PATH env var with Mint17.3 within the 
.profile file, after upgrade to Mint18, this configuration has been 
copied over to the new .profile file, but included within the IF 
statement. That is wrong, because it will never be called since I do not 
have a $HOME/bin folder. Hence, we shouldn't close this issue.

What do you think?

Cheers,
Peter

Am 30.07.2016 um 13:50 schrieb Clement Lefebvre:
