### ISSUE TITLE
Some problems, many of them cosmetic but nonetheless somewhat important

### ISSUE THREAD

**Issue by ghost** [linuxmint/mintupgrade-legacy#11]
1. The upgrade tool, in its 'check' mode - and presumably in its actual, doing-it mode - does not tell one how to restore the PPAs that it removes. This is not good. True, at the end of the checking run, the sources are restored automatically - but the user should not been told this would happen, I feel. EDIT: at the end of the upgrade process, and perhaps because the process encountered some problems, my PPAs were not in fact restored.

2. At the end of a seemingly successful checking run, no indication of success is given.

3. I received multiple messages about how APT would now download the needed packages (and the message did say 'the' and not 'some' or just - i.e. with no article - 'needed packages'). These repeated messages made me think, 'Hold on, haven't I just done this?'

I know the tool is not meant for novices, but (i) novices will use it anyway, (ii) I am not a novice but 1-3 threw me nonetheless.

Also, 

4. Having Chrony installed seemed to abort the upgrade.

5. The message upon the abort suggested I try again (after using `apt` to fix the problem). The message *means*, I take it, repeat `mintupgade upgrade` - but this should be clearer, I feel. (I removed chrony and repeated that command and this time I did not encounter the error message - though I did run into one about Samba . .)

6. It's worth warning the user s/he will have to accept (yes?) some font licensing terms.

Thank you for your work and for making an in-place upgrade possible.

**Comment by clefebvre** [comment]
Can you elaborate on the issues with chrony and samba? What error messages from APT do you get?

**Comment by ghost** [comment]
I am sorry, but I fear I no longer have a record - unless you can direct me to my apt logs. (For, I forget how to do that.) All I recall is that in each case - chrony and Samba - there was a message (in red I believe) saying that the installation could not continue.

**Comment by ghost** [comment]
I've managed to get the samba service working, but I cannot connect from Windows to Linux (Linux to Windows works) and, also, I cannot get the 'cgmanager' service to start.

**Comment by CottonEaster** [comment]
I am finding this very frustrating - I wrote a 4,000 word guide on how to get file sharing working between Linux and Windows (which is something Linux is meant to be good at) and I still cannot get it working.

**Comment by ghost** [comment]
Please see this bug report on Samba: https://github.com/linuxmint/Cinnamon/issues/7702
