### ISSUE TITLE
Error Message when executing mintupgrade

### ISSUE THREAD

**Issue by cglaeser** [linuxmint/mintupgrade-legacy#13]
The error message: 
------------------------------------------------
!!  ERROR: Please set up system snapshots. If anything goes wrong with the upgrade, snapshots will allow you to restore your operating system. Install and configure Timeshit, and create a snapshot before proceeding with the upgrade.
!!  Exiting.
------------------------------------------------
contains a typo: 'Timeshit' probably means 'Timeshift'?

**Comment by JosephMcc** [comment]
Thanks for the report. This is already fixed.
