### ISSUE TITLE
Upgrade Linux Mint 18.3 to 19 with logo "Ubuntu"(?!)

### ISSUE THREAD

**Issue by DorianB2017** [linuxmint/mintupgrade-legacy#14]
For Clem
Hello!

After upgrading from Linux Mint 18.3 to Linux Mint 19.0 (I used mintupgrade v. 18.3.7), following the instructions here https://community.linuxmint.com/tutorial/view/2416, I woke up at the first reboot with the logo "Ubuntu 19" (???!!!) instead by the "Linux Mint" logo and The Cinnamon graphics environment is crash permanently.

I discovered that the upgrade today, July 5, contains files for the Mate interface, I have Linux Mint Cinnamon

Please fix these bugs.

Sorry for my poor English.

Best regards,
Dorian B.

Update info (July 6, 2018):
After upgraded to Linux Mint 19 Cinnamon, there are installed: mate-menu, mate-desktop, mate-common ... (???!!!). I use Linux Mint Cinnamon with the Romanian language.
![cinnamon crash](https://user-images.githubusercontent.com/30018486/42377127-972a0512-812a-11e8-9cb9-60422c9ef939.png)

**Comment by ergonomicus** [comment]
Same thing here!

**Comment by JosephMcc** [comment]
> I discovered that the upgrade today, July 5, contains files for the Mate interface, I have Linux Mint Cinnamon

The Mate parts are there to provide a fallback for when Cinnamon crashes so you have a usable desktop. It's intentional, not an error of any sort.
