### ISSUE TITLE
Preferences: Option "Always select kernel updates" doesn't work

### ISSUE THREAD

**Issue by BLaDZer** [linuxmint/mintupgrade-legacy#15]
Linux Mint 19 (updated from Linux Mint 18.3).

Everytime you click "Refresh" button checkbox will be automatically checked(selected).

I doesn't check other options cuz not worry about them. But they can be affected by this bug too.

![screenshot from 2018-07-06 17-55-48](https://user-images.githubusercontent.com/13044587/42382861-9496959c-8146-11e8-95b3-820a0a5ed8d7.png)

**Comment by xenopeek** [comment]
On the Levels tab in Preferences you likely have level 4 set to Visible and Selected. The "Always select kernel updates" overrides that setting, if you haven't set level 4 to Selected. If you disable "Always select kernel updates" but leave level 4 to Selected, indeed it still selects it.

**Comment by BLaDZer** [comment]
@xenopeek so is it possible to select all from 4 level except the kernel??

**Comment by xenopeek** [comment]
No, level 4 is the kernel and other packages directly related to boot and login. You can select the kernel and deselect/hide the other level 4 packages but not the other way around. General recommendation is to install all updates and use Timeshift to rollback if an update does cause problems. You can also boot your previous kernel from the GRUB boot menu (hold down shift key after turning on your computer to make that appear if it doesn't show by default).
