### ISSUE TITLE
Some packages didn't upgrade from 18.3 to 19 due to version numbering

### ISSUE THREAD

**Issue by ewangi** [linuxmint/mintupgrade-legacy#18]
Just a note that several Flatpak-related packages didn't upgrade on my i386 Mint MATE system when carrying out directly subsequent in-situ upgrades from 18.3 to 19 and then to 19.1. This appears to be due to an unexpected drop in version numbers.

These are:

_xdg-desktop-portal_ and _xdg-desktop-portal-gtk_: not upgraded from 1.0.2-flatpak1~xenial to 0.11-1.

_gir1.2-flatpack-1.0_ and _libflatpak0_: not upgraded from 1.0.3-flatpak1~xenial to 1.0.1-0ubuntu0.1.

These anomalies were found by grepping the output of dpkg -l for occurrences of "xenial".

**Comment by clefebvre** [comment]
This is fine now, except for xdg-desktop-portal-gtk which requires mintsources to be used to downgrade it to repo version.

I'll add an item to the roadmap to maybe list/address foreign packages post-upgrade within mintupgrade.
