### ISSUE TITLE
Idea for improving mintupgrade

### ISSUE THREAD

**Issue by alan7000** [linuxmint/mintupgrade-legacy#19]
Hello, I'm creating this issue for a little idea for novice or lambda users. Currently the tool runs entirely on the command line. I propose that it become a graphical tool with two parts. The first part would be to present the update, download the packages and create a temporary entry in grub to start as root only. The second part would be to install all the packages and remove the temporary entry in grub. I don't know if this solution is the right one for you but it will allow everyone to update the distribution without too much difficulty.

**Comment by clefebvre** [comment]
Thank you for the idea. We're interested in making it graphical but due to the complexity of the upgrade process and the importance of the commands output we're keeping it command-line for now.
