### ISSUE TITLE
Problem: Held packages are not handled

### ISSUE THREAD

**Issue by gm10** [linuxmint/mintupgrade-legacy#20]
This needs to unhold all held packages first. Will become even more relevant going from 19.3 to 20 with Pjotr unfortunately recommending on his popular easy linux tips website to put level 4 packages on hold in preparation for the removal of levels.

**Comment by LinuxOnTheDesktop** [comment]
Why is this closed, please? Are held packages now handled? The [upgrade instructions](https://community.linuxmint.com/tutorial/view/2485) do not mention held packages.

**Comment by nMustaki** [comment]
Hi, just wanted to say I got bitten by this, I had completly forgotten that some core packages were on hold and almost break my system when trying to force the upgrade manually.
A warning would be very useful !
