### ISSUE TITLE
on besty leaf to upgrade from lmde 2 to lmde 3 Mate edition is not supported

### ISSUE THREAD

**Issue by lutin11** [linuxmint/mintupgrade-legacy#23]
SUPPORTED_EDITIONS = ["cinnamon", "MATE"]

**Comment by clefebvre** [comment]
That's by design, MATE isn't maintained in LMDE 3.

**Comment by lutin11** [comment]
> That's by design, MATE isn't maintained in LMDE 3.

OK, thank you for replying . Is cinamon lighter as Mate. I uses ut on first Acre Aspire One , originally designed to use Linux. It's a 32b processor
