### ISSUE TITLE
`mintupgrade` can restore an old apt backup from a previous upgrade

### ISSUE THREAD

**Issue by sruggier** [linuxmint/mintupgrade-legacy#24]
I'm, admittedly, terrible at following directions, but this looks like it could be a potentially serious issue for anyone not comfortable managing apt configuration directly: I ran `mintupgrade check`, it failed before the point where it takes a backup, and then it restored an old backup from when I upgraded from Betsy to Cindy. It was a pretty amusingly bad failure mode to see a bunch of Jessie and Betsy sources in apt-get upgrade after the check failed.

It looks like the problem I observed was that the script was in `prepare`, and it called `self.fail`, which is only safe if the `BACKUP_APT_SOURCES` path either doesn't exist, or exists and is a copy of the user's apt sources immediately before mintupgrade was called. However, in my case the path existed, and contained an old backup from when my system was still on Betsy.

Here are my suggestions for how to fix this ranked from best to easiest:
* This one is safer, because it doesn't delete old backups:
  1. Store backups at a path that includes a timestamp. Given the size of apt sources, this shouldn't waste enough space to worry about.
  2. Make a backup at the top of `prepare` before doing anything else
  3. Modify `restore_sources` to use the latest backup
  4. Don't delete backups during restoration 
* This is slightly less safe, but easier:
  1. Make a backup at the top of `prepare before doing anything else. If an existing backup is there, delete it first.
* This is a bit more efficient, but maybe more error prone than the other two options:
  1. At the top of `prepare`, remove any existing apt backups. No other changes needed.

**Comment by clefebvre** [comment]
fixed by https://github.com/linuxmint/mintupgrade/commit/bed46cd6856c7a357d642c650198f6859c144f71
