### ISSUE TITLE
Error during mint upgrade 

### ISSUE THREAD

**Issue by razerrazer** [linuxmint/mintupgrade-legacy#28]
The following packages have unmet dependencies:
 aptitude : Depends: libapt-pkg5.0 (>= 1.1) but it is not installable
 caja-admin : Depends: python-gi but it is not installed
 hplip : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 libapt-inst2.0 : Depends: libapt-pkg5.0 (>= 1.1~exp9) but it is not installable
 libapt-pkg-perl : Depends: perlapi-5.26.1 but it is not installable
                   Depends: libapt-pkg5.0 (>= 1.1~exp9) but it is not installable
 libcairo-perl : Depends: perlapi-5.26.1 but it is not installable
 libcommon-sense-perl : Depends: perlapi-5.26.1 but it is not installable
                        Depends: perl (< 5.26.2~) but 5.30.0-9build1 is installed
 libept1.5.0 : Depends: libapt-pkg5.0 (>= 1.1~exp9) but it is not installable
 libfcgi-perl : Depends: perlapi-5.26.0 but it is not installable
 libfile-fcntllock-perl : Depends: perlapi-5.26.0 but it is not installable
 libglib-perl : Depends: perlapi-5.26.0 but it is not installable
 libgtk2-perl : Depends: perlapi-5.26.0 but it is not installable
 libharfbuzz-dev : Depends: gir1.2-harfbuzz-0.0 (= 2.6.4-1ubuntu4) but 1.7.2-1ubuntu1 is installed
 libhtml-parser-perl : Depends: perlapi-5.26.0 but it is not installable
 libimage-magick-q16-perl : Depends: perlapi-5.26.1 but it is not installable
 libio-pty-perl : Depends: perlapi-5.26.0 but it is not installable
 liblist-moreutils-perl : Depends: perlapi-5.26.0 but it is not installable
 liblocale-gettext-perl : PreDepends: perlapi-5.26.0 but it is not installable
 libnet-dbus-perl : Depends: perlapi-5.26.0 but it is not installable
 libnet-libidn-perl : Depends: perlapi-5.26.0 but it is not installable
 libpango-perl : Depends: perlapi-5.26.0 but it is not installable
 libperlio-gzip-perl : Depends: perlapi-5.26.0 but it is not installable
 libsocket6-perl : Depends: perlapi-5.26.0 but it is not installable
 libsub-name-perl : Depends: perlapi-5.26.0 but it is not installable
 libtext-charwidth-perl : Depends: perlapi-5.26.0 but it is not installable
 libtext-iconv-perl : Depends: perlapi-5.26.0 but it is not installable
 libuuid-perl : Depends: perlapi-5.26.0 but it is not installable
 libxml-parser-perl : Depends: perlapi-5.26.0 but it is not installable
 onboard : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 python-gi-cairo : Depends: python-gi (= 3.26.1-2ubuntu1) but it is not installed
 python3-apt : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
               Depends: libapt-pkg5.0 (>= 1.6.5~) but it is not installable
 python3-brlapi : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 python3-cairo : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 python3-crypto : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 python3-cups : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 python3-dbus : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 python3-gi-cairo : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
                    Depends: python3-gi (= 3.26.1-2ubuntu1) but 3.36.0-1 is installed
 python3-pycurl : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 synaptic : Depends: libapt-pkg5.0 (>= 1.1~exp9) but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

All checks and everything went through. But i had to reset the system back via USB and timeshift

**Comment by clefebvre** [comment]
Which PPAs were you using if any?

**Comment by razerrazer** [comment]
Hi Clefebvre, I use some PPAs see attached file.

![image](https://user-images.githubusercontent.com/17000974/87182684-e6478400-c2e4-11ea-9178-93e07aab06de.png)

**Comment by razerrazer** [comment]
I tried to remove every PPAs except of these:

![image](https://user-images.githubusercontent.com/17000974/87192931-d7b69800-c2f7-11ea-9859-48575b6ac1b6.png)

But the problem remains, i had to take it back from backup again.

  + Running fallback command 'sudo apt-get install -fyq'...
Reading package lists...
Building dependency tree...
Reading state information...
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra dh-python grub2-theme-mint libart-2.0-2 libatomic1:i386 libbonobo2-0 libbonobo2-common libbonoboui2-0
  libbonoboui2-common libcom-err2:i386 libdb5.3:i386 libdrm-amdgpu1:i386 libdrm-intel1:i386 libdrm-nouveau2:i386 libdrm-radeon1:i386
  libdrm2:i386 libedit2:i386 libelf1:i386 libexpat1:i386 libffi6:i386 libffi7:i386 libglapi-mesa:i386 libglvnd0:i386 libgnome-2-0
  libgnome2-common libgnomecanvas2-0 libgnomecanvas2-common libgnomeui-0 libgnomeui-common libgnomevfs2-0 libgnomevfs2-common
  libgraphicsmagick++1-dev libgraphicsmagick1-dev libidl-2-0 libllvm9:i386 libncurses5:i386 liborbit-2-0 liborbit2 libpangox-1.0-0
  libpciaccess0:i386 libpcre3:i386 libpython-dev libstdc++6:i386 libtiff5-dev libtinfo5:i386 libwebp-dev libx11-xcb1:i386 libxcb-dri2-0:i386
  libxcb-dri3-0:i386 libxcb-glx0:i386 libxcb-present0:i386 libxcb-sync1:i386 libxdamage1:i386 libxfixes3:i386 libxshmfence1:i386
  libxxf86vm1:i386 libzstd-dev linux-generic-hwe-18.04 linux-headers-generic-hwe-18.04 linux-hwe-5.4-headers-5.4.0-39
  linux-hwe-5.4-headers-5.4.0-40 linux-image-5.3.0-62-generic linux-image-generic-hwe-18.04 linux-modules-5.3.0-62-generic
  linux-modules-extra-5.3.0-62-generic python-pip-whl
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  aptitude aptitude-common aspell caja-admin compizconfig-settings-manager crudini gir1.2-harfbuzz-0.0 gir1.2-rsvg-2.0 gtk-doc-tools
  libapt-pkg-perl libaspell15 libbrlapi0.7 libcairo-perl libcairo-script-interpreter2 libcairo2-dev libcommon-sense-perl libcwidget4
  libdjvulibre-dev libdjvulibre21 libenchant-2-2 libept1.6.0 libfcgi-perl libfile-fcntllock-perl libfontconfig1-dev libgdk-pixbuf2.0-dev
  libglib-perl libgspell-1-2 libgtk2-perl libhtml-parser-perl libilmbase-dev libimage-magick-q16-perl libio-pty-perl liblist-moreutils-perl
  liblocale-gettext-perl liblqr-1-0-dev libmagick++-6-headers libmagick++-6.q16-8 libmagick++-6.q16-dev libmagick++-dev
  libmagickcore-6-arch-config libmagickcore-6-headers libmagickcore-6.q16-6 libmagickcore-6.q16-6-extra libmagickcore-6.q16-dev
  libmagickwand-6-headers libmagickwand-6.q16-6 libmagickwand-6.q16-dev libnet-dbus-perl libnet-libidn-perl libopenexr-dev libpango-perl
  libperlio-gzip-perl libpixman-1-dev libpython2-stdlib librsvg2-dev libsocket6-perl libsub-name-perl libtext-charwidth-perl libtext-iconv-perl
  libuuid-perl libvulkan1 libvulkan1:i386 libxapian30 libxcb-render0-dev libxcb-shm0-dev libxml-parser-perl libxrender-dev libxt-dev libzbar-dev
  libzbar0 onboard onboard-common printer-driver-postscript-hp python-cairo python-caja-common python-crypto python-dbus python-enum34
  python-funcsigs python-gi python-gi-cairo python-gobject-2 python-mock python-numpy python-pbr python-pil python-pkg-resources python-pypdf2
  python-setproctitle python-setuptools python-sip python-six python-xdg python-xlib python2 python2-minimal python3-apt python3-brlapi
  python3-cairo python3-caja python3-compizconfig python3-crypto python3-cups python3-dbus python3-gi-cairo python3-iniparse python3-lxml
  python3-pycurl python3-pygments synaptic xed xed-common xed-dbg
Suggested packages:
  aptitude-doc-en | aptitude-doc apt-xapian-index debtags tasksel aspell-doc spellutils dblatex libfont-freetype-perl libcairo2-doc
  libcwidget-dev libenchant-2-voikko libgtk2-perl-doc inkscape libjxr-tools librsvg2-doc xapian-tools libxt-doc hplip python-dbus-dbg
  python-dbus-doc python-enum34-doc python-funcsigs-doc python-gobject-2-dbg python-mock-doc gfortran python-dev python-pytest python-numpy-dbg
  python-numpy-doc python-pil-doc python-pil-dbg python-setuptools-doc python2-doc python-tk python3-apt-dbg python-apt-doc python3-dbus-dbg
  python3-lxml-dbg python-lxml-doc libcurl4-gnutls-dev python-pycurl-doc python3-pycurl-dbg python-pygments-doc ttf-bitstream-vera dwww menu
  deborphan software-properties-gtk
Recommended packages:
  pluma enchant-2 mesa-vulkan-drivers | vulkan-icd mesa-vulkan-drivers:i386 | vulkan-icd:i386 onboard-data python-olefile python3-html5lib
The following packages will be REMOVED:
  fahcontrol graphicsmagick-libmagick-dev-compat hplip libapt-inst2.0 libept1.5.0 libpython-stdlib libsensors4:i386 mate-sensors-applet python
  python-caja python-compizconfig python-configobj python-dev python-gconf python-glade2 python-gnome2 python-gtk2 python-iniparse python-ldb
  python-minimal python-notify python-opencv python-parted python-pip python-pyorbit python-qt4 python-qt4-dbus python-reportlab
  python-reportlab-accel python-zbar
The following NEW packages will be installed:
  gir1.2-rsvg-2.0 libbrlapi0.7 libcairo-script-interpreter2 libcairo2-dev libcwidget4 libdjvulibre-dev libenchant-2-2 libept1.6.0
  libfontconfig1-dev libgdk-pixbuf2.0-dev libgspell-1-2 libilmbase-dev liblqr-1-0-dev libmagick++-6-headers libmagick++-6.q16-8
  libmagick++-6.q16-dev libmagick++-dev libmagickcore-6-arch-config libmagickcore-6-headers libmagickcore-6.q16-6 libmagickcore-6.q16-6-extra
  libmagickcore-6.q16-dev libmagickwand-6-headers libmagickwand-6.q16-6 libmagickwand-6.q16-dev libopenexr-dev libpixman-1-dev libpython2-stdlib
  librsvg2-dev libxcb-render0-dev libxcb-shm0-dev libxrender-dev libxt-dev python-enum34 python-gi python-setuptools python2 python2-minimal
  python3-caja python3-compizconfig python3-iniparse python3-lxml python3-pygments
The following packages will be upgraded:
  aptitude aptitude-common aspell caja-admin compizconfig-settings-manager crudini gir1.2-harfbuzz-0.0 gtk-doc-tools libapt-pkg-perl libaspell15
  libcairo-perl libcommon-sense-perl libdjvulibre21 libfcgi-perl libfile-fcntllock-perl libglib-perl libgtk2-perl libhtml-parser-perl
  libimage-magick-q16-perl libio-pty-perl liblist-moreutils-perl liblocale-gettext-perl libnet-dbus-perl libnet-libidn-perl libpango-perl
  libperlio-gzip-perl libsocket6-perl libsub-name-perl libtext-charwidth-perl libtext-iconv-perl libuuid-perl libvulkan1 libvulkan1:i386
  libxapian30 libxml-parser-perl libzbar-dev libzbar0 onboard onboard-common printer-driver-postscript-hp python-cairo python-caja-common
  python-crypto python-dbus python-funcsigs python-gi-cairo python-gobject-2 python-mock python-numpy python-pbr python-pil python-pkg-resources
  python-pypdf2 python-setproctitle python-sip python-six python-xdg python-xlib python3-apt python3-brlapi python3-cairo python3-crypto
  python3-cups python3-dbus python3-gi-cairo python3-pycurl synaptic xed xed-common xed-dbg
70 upgraded, 43 newly installed, 30 to remove and 658 not upgraded.
20 not fully installed or removed.
Need to get 0 B/32,4 MB of archives.
After this operation, 33,2 MB of additional disk space will be used.
Extracting templates from packages: 100%
Setting up python3 (3.8.2-0ubuntu2) ...
running python rtupdate hooks for python3.8...
E: py3compile:183: cannot create directory /usr/share/hplip/ui5/__pycache__: FileNotFoundError(2, 'No such file or directory')
/usr/share/hplip/base/utils.py:2061: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if weburl is "" or weburl is None:
/usr/share/hplip/check-plugin.py:116: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if log_level is 'debug':
/usr/share/hplip/check.py:685: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if 'getfacl' not in g and '' is not g and 'file' not in g:
/usr/share/hplip/installer/core_install.py:2074: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if home_dir is "":
Traceback (most recent call last):
  File "/usr/lib/python3.8/py_compile.py", line 197, in main
    compile(filename, doraise=True)
  File "/usr/lib/python3.8/py_compile.py", line 142, in compile
    source_bytes = loader.get_data(file)
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/hplip/ui5/aboutdialog.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/py_compile.py", line 218, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/py_compile.py", line 204, in main
    if quiet < 2:
NameError: name 'quiet' is not defined
error running python rtupdate hook hplip-data
dpkg: error processing package python3 (--configure):
 installed python3 package post-installation script subprocess returned error exit status 4
dpkg: dependency problems prevent configuration of python3-gi:
 python3-gi depends on python3 (<< 3.9); however:
  Package python3 is not configured yet.
 python3-gi depends on python3 (>= 3.8~); however:
  Package python3 is not configured yet.
 python3-gi depends on python3:any; however:
  Package python3 is not configured yet.

dpkg: error processing package python3-gi (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          Errors were encountered while processing:
 python3
 python3-gi
E: Sub-process /usr/bin/dpkg returned an error code (1)

  + An issue was detected during the upgrade, running dist-upgrade in manual mode....
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 aptitude : Depends: libapt-pkg5.0 (>= 1.1) but it is not installable
 caja-admin : Depends: python-gi but it is not installed
 hplip : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 libapt-inst2.0 : Depends: libapt-pkg5.0 (>= 1.1~exp9) but it is not installable
 libapt-pkg-perl : Depends: perlapi-5.26.1 but it is not installable
                   Depends: libapt-pkg5.0 (>= 1.1~exp9) but it is not installable
 libcairo-perl : Depends: perlapi-5.26.1 but it is not installable
 libcommon-sense-perl : Depends: perlapi-5.26.1 but it is not installable
                        Depends: perl (< 5.26.2~) but 5.30.0-9build1 is installed
 libept1.5.0 : Depends: libapt-pkg5.0 (>= 1.1~exp9) but it is not installable
 libfcgi-perl : Depends: perlapi-5.26.0 but it is not installable
 libfile-fcntllock-perl : Depends: perlapi-5.26.0 but it is not installable
 libglib-perl : Depends: perlapi-5.26.0 but it is not installable
 libgtk2-perl : Depends: perlapi-5.26.0 but it is not installable
 libharfbuzz-dev : Depends: gir1.2-harfbuzz-0.0 (= 2.6.4-1ubuntu4) but 1.7.2-1ubuntu1 is installed
 libhtml-parser-perl : Depends: perlapi-5.26.0 but it is not installable
 libimage-magick-q16-perl : Depends: perlapi-5.26.1 but it is not installable
 libio-pty-perl : Depends: perlapi-5.26.0 but it is not installable
 liblist-moreutils-perl : Depends: perlapi-5.26.0 but it is not installable
 liblocale-gettext-perl : PreDepends: perlapi-5.26.0 but it is not installable
 libnet-dbus-perl : Depends: perlapi-5.26.0 but it is not installable
 libnet-libidn-perl : Depends: perlapi-5.26.0 but it is not installable
 libpango-perl : Depends: perlapi-5.26.0 but it is not installable
 libperlio-gzip-perl : Depends: perlapi-5.26.0 but it is not installable
 libsocket6-perl : Depends: perlapi-5.26.0 but it is not installable
 libsub-name-perl : Depends: perlapi-5.26.0 but it is not installable
 libtext-charwidth-perl : Depends: perlapi-5.26.0 but it is not installable
 libtext-iconv-perl : Depends: perlapi-5.26.0 but it is not installable
 libuuid-perl : Depends: perlapi-5.26.0 but it is not installable
 libxml-parser-perl : Depends: perlapi-5.26.0 but it is not installable
 onboard : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 python-gi-cairo : Depends: python-gi (= 3.26.1-2ubuntu1) but it is not installed
 python3-apt : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
               Depends: libapt-pkg5.0 (>= 1.6.5~) but it is not installable
 python3-brlapi : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 python3-cairo : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 python3-crypto : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 python3-cups : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 python3-dbus : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 python3-gi-cairo : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
                    Depends: python3-gi (= 3.26.1-2ubuntu1) but 3.36.0-1 is installed
 python3-pycurl : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 synaptic : Depends: libapt-pkg5.0 (>= 1.1~exp9) but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

**Comment by razerrazer** [comment]
This issue have been solved, i removed everything under PPAs + Removed everything under Additional repository's :

Removed all foreign packages and downgraded foreign packages.
