### ISSUE TITLE
re-enable PPA

### ISSUE THREAD

**Issue by timmie** [linuxmint/mintupgrade-legacy#3]
please include an option to 
- back up PPAs before upgrade
- re-enable PPAs after upgrade

**Comment by brozkeff** [comment]
In addition to that it would be nice if the upgrade tool could offer an OPTIONAL action of rewriting distribution version in the ppas (replace "trusty" to "xenial") IF the ppa repo contains the packages for xenial already...

**Comment by alpharesearch** [comment]
At least add very important PPAs like Google Chrome back so that users don't miss critical security updates.

**Comment by xenopeek** [comment]
Thanks for contributing to mintupgrade. Your suggestion was reviewed. For more information on our workflow and feature requests, read: https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
