### ISSUE TITLE
Performing an upgrade leaves users who have snapd installed with an out-of-date version

### ISSUE THREAD

**Issue by dmcdo** [linuxmint/mintupgrade-legacy#32]
Performing an upgrade from Linux Mint 19.3 to 20 will create a `nosnap.pref` file even if `snapd` has already been installed. Since `snapd` still remains on the system after the upgrade, whatever version of `snapd` was on the installation at the time of upgrade will never be updated, leaving that system open to potential security vulnerabilities and breakages without the person who performed the upgrade having any knowledge as to how or why.

![Screenshot_20200710_192456](https://user-images.githubusercontent.com/40744272/87210478-a59b3b00-c2e3-11ea-9903-4e6e5be47cc5.png)

**Comment by razerrazer** [comment]
Check this thread https://www.omgubuntu.co.uk/2020/06/enable-snap-apps-linux-mint-20

**Comment by dmcdo** [comment]
The disabling of snaps isn't the issue here. The issue in this situation is that snaps had already been enabled prior to and continue to be enabled after the upgrade, but because the `nosnap.pref` file is created, `snapd` is blocked from updating.

**Comment by dmcdo** [comment]
Looking into it further, the issue appears to reside with the `ubuntu-system-adjustments` package, so I am submitting the issue to the linuxmint repository and closing this one as it is in the wrong place.
