### ISSUE TITLE
Help manually remove packages (via dpkg --purge) that break even apt-get -f install

### ISSUE THREAD

**Issue by brozkeff** [linuxmint/mintupgrade-legacy#4]
I just succesfully migrated my Mint 17.3 Xfce 64bit (gradually updated from 17 to 17.1 to 17.2, with a lot of config files copied from earlier Mint 13 MATE 32bit) to 18 using the upgrade manual and mintupgrade v17.3.10.

It required some hacking, however, due to some problematic packages that I installed manually or from different PPAs. The apt upgrade process was terminated 4 or 5 times with different packages and even apt-get -f install could not fix it; I had to re-iterate these steps to get to the finish:

1) remove these offending packages with the command
dpkg --purge --force-all PACKAGENAME

2) apt-get -f install

3) mintupgrade upgrade

I repeated steps 1-3 as many times as needed, according to the errors that appear at the end of the prematurely failed mintupgrade upgrade step.

It would help a lot if the mintupgrade could detect this type of error and offer to force uninstall and purge these packages and fix apt-get and try again, or at least when terminating prematurely, offer such a tip to the user. After doing all this (and working with the system at the same time as usual) and rebooting everything seems to work perfectly.

Less experienced user (and I have seen already a few desperate users in the comments and forums experiencing this issue and not being able to cope with it) will have a major problem when such a thing happens. Removing a few packages (and then reinstalling them manually after the upgrade if still needed) is less harm than doing a complete re-install from scratch.

The packages I had problems with included
- libde265 from a PPA, colliding with the native one
- kdenlive from a PPA
- zram-config
  and some other packages I don't remember

**Comment by xenopeek** [comment]
Thanks for contributing to mintupgrade. Your suggestion was reviewed. For more information on our workflow and feature requests, read: https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
