### ISSUE TITLE
zram_config_0.5_all.deb causes interruption

### ISSUE THREAD

**Issue by alpharesearch** [linuxmint/mintupgrade-legacy#5]
I was using Mint 17.3 Mate with all the updates before the upgrade.
1. The upgrade stops with this error messages on two computers (a VM and a Chromebook with SEA bios):
   Errors were encountered while processing:
   /var/cache/apt/archives/zram_config_0.5_all.deb
   E: Sub-process /usr/bin/dpkg returned an error code (1)
   (it looks like the startup script  fro zram is missing something)

After it stops I just run the upgrade command again and it finishes successful and so far I don't had any issues with Mint 18.
1. However I was wondering if it was OK for me to select the yes answer if I want the maintainers version of all the config file when it asked? I guess no is the default and preferred answer, however I was thinking because of large version differences yes may be better because of newer defaults.
2. after the upgrade finishes it would be nice to at least add very populare PPAs like google and steam back.

Thanks for your hard work and otherwise I think this upgrade program worked really well.

**Comment by brozkeff** [comment]
This is not just the case with zram_config, I had this package and was using zram on 17.3 as well and I encountered the same issue, but I had a similar problem with about 5 other packages - most of the others were however "sideloaded" from PPAs or deb files directly or pinpointed from earlier versions of Ubuntu etc., so perhaps it's correct that the focus should be put mostly on the packages that could be installed from the base Mint or Ubuntu repository...

**Comment by alpharesearch** [comment]
Yes I think it should be able to handle official packages without issues first, however if it can be implemented to handle any other package as well that would be good too. In the end it would be better to just keep trying at least once more automatically in my opinion...

There is one glitch I found just now, the Mint-Y-(Darker) theme is complaining that adwaita theme engine is missing... but if I compare the upgrade Mint 18 with a real install Mint 18 I don't see any difference and the adwaita-icon-theme package is installed... anyway it looks exactly the same on both VMs if I toggle the screen back and forward between the two? I guess everything is working but appearance preferences shows an wrong error message? (but I only had this on the VM upgrade and not on the Chromebook upgrade).

**Comment by xenopeek** [comment]
Thanks for contributing to mintupgrade. Your suggestion was reviewed. For more information on our workflow and feature requests, read: https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
