### ISSUE TITLE
mintupgrade-legacy for Mint Main Edition Upgrade

### ISSUE THREAD

**Issue by eband** [linuxmint/mintupgrade-legacy#57]
Can I use mintupgrade (not mintupgrade2( to upgrade my Mint 20.3 like ages past?

**Comment by xenopeek** [comment]
mintupgrade for upgrading Linux Mint 19.3 to 20 is renamed to mintupgrade-legacy and isn't supported for upgrading 20.3 to 21.

**Comment by eband** [comment]
Which tool should I use if I still want to use the command line (or Cubic) to upgrade to 21?

**Comment by xenopeek** [comment]
Text editor and apt tools.

**Comment by Jeremy7701** [comment]
Has Mint 21 been released yet?

**Comment by eband** [comment]
No, wait until July.
