### ISSUE TITLE
mintupgrade overwrites ~/.bashrc with /etc/skel/.bashrc

### ISSUE THREAD

**Issue by jhankins2** [linuxmint/mintupgrade-legacy#6]
Commit d3a8baa07b2364d9562d21ebaeb921b3ce89056f causes mintupgrade to overwrite existing ~/.bashrc.

**Comment by exciton** [comment]
Agreed - this is terrible!

**Comment by PaulXiCao** [comment]
is there a reason why we should recreate the bashrc file? is there maybe a need for the upgrade process to work where each user needs at least some basic bashrc?

anyways, i will just propose a pull request which removes this overwrite process.
