### ISSUE TITLE
mintupgrade overwrites modified config files in /etc

### ISSUE THREAD

**Issue by szeder** [linuxmint/mintupgrade-legacy#7]
I was suspicious that there were barely any questions to answer during the upgrade process from 17.3 to 18.  The first boot into the upgraded system quickly showed why: the upgrade process overwrote config files _with local modifications_, resulting in a number of things not working properly or not working at all.
This shouldn't happen.

Now I have to wade through all those `/etc/*.dpkg-old` files, great.

**Comment by xenopeek** [comment]
Thanks for contributing to mintupgrade. Your suggestion was reviewed. For more information on our workflow and feature requests, read: https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html

**Comment by szeder** [comment]
This is neither a "suggestion" nor an "idea", but a bug report about a serious flaw of the upgrade process.
